const card_list = [ // Lista delle carte che comporranno il mazzo, con le relative informazioni
    {
        "name": "Bang!",
        "number": "2",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_2_F.png"
    },
    {
        "name": "Bang!",
        "number": "3",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_3_F.png"
    },
    {
        "name": "Bang!",
        "number": "4",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_4_F.png"
    },
    {
        "name": "Bang!",
        "number": "5",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_5_F.png"
    },
    {
        "name": "Bang!",
        "number": "6",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_6_F.png"
    },
    {
        "name": "Bang!",
        "number": "7",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_7_F.png"
    },
    {
        "name": "Bang!",
        "number": "8",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_8_F.png"
    },
    {
        "name": "Bang!",
        "number": "9",
        "suit": "F",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_9_F.png"
    },
    {
        "name": "Bang!",
        "number": "2",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_2_Q.png"
    },
    {
        "name": "Bang!",
        "number": "3",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_3_Q.png"
    },
    {
        "name": "Bang!",
        "number": "4",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_4_Q.png"
    },
    {
        "name": "Bang!",
        "number": "5",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_5_Q.png"
    },
    {
        "name": "Bang!",
        "number": "6",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_6_Q.png"
    },
    {
        "name": "Bang!",
        "number": "7",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_7_Q.png"
    },
    {
        "name": "Bang!",
        "number": "8",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_8_Q.png"
    },
    {
        "name": "Bang!",
        "number": "9",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_9_Q.png"
    },
    {
        "name": "Bang!",
        "number": "10",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_10_Q.png"
    },
    {
        "name": "Bang!",
        "number": "11",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_11_Q.png"
    },
    {
        "name": "Bang!",
        "number": "12",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_12_Q.png"
    },
    {
        "name": "Bang!",
        "number": "13",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_13_Q.png"
    },
    {
        "name": "Bang!",
        "number": "14",
        "suit": "Q",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_14_Q.png"
    },
    {
        "name": "Bang!",
        "number": "12",
        "suit": "C",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_12_C.png"
    },
    {
        "name": "Bang!",
        "number": "13",
        "suit": "C",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_13_C.png"
    },
    {
        "name": "Bang!",
        "number": "14",
        "suit": "C",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_14_C.png"
    },
    {
        "name": "Bang!",
        "number": "14",
        "suit": "P",
        "color": "marrone",
        "action": "colpo",
        "ability": "Puoi giocare solo una carta Bang! per turno.",
        "range": "visibile",
        "quantity": "0",
        "img": "Bang!_14_P.png"
    },
    {
        "name": "Duello",
        "number": "12",
        "suit": "Q",
        "color": "marrone",
        "action": "duello",
        "ability": "Un giocatore scarta un BANG!, poi tu, ecc. Il primo che non lo fa perde 1 punto vita.",
        "range": "qualsiasi_altro",
        "quantity": "0",
        "img": "Duello_12_Q.png"
    },
    {
        "name": "Duello",
        "number": "11",
        "suit": "P",
        "color": "marrone",
        "action": "duello",
        "ability": "Un giocatore scarta un BANG!, poi tu, ecc. Il primo che non lo fa perde 1 punto vita.",
        "range": "qualsiasi_altro",
        "quantity": "0",
        "img": "Duello_11_P.png"
    },
    {
        "name": "Duello",
        "number": "8",
        "suit": "F",
        "color": "marrone",
        "action": "duello",
        "ability": "Un giocatore scarta un BANG!, poi tu, ecc. Il primo che non lo fa perde 1 punto vita.",
        "range": "qualsiasi_altro",
        "quantity": "0",
        "img": "Duello_8_F.png"
    },
    {
        "name": "Mancato!",
        "number": "10",
        "suit": "F",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_10_F.png"
    },
    {
        "name": "Mancato!",
        "number": "11",
        "suit": "F",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_11_F.png"
    },
    {
        "name": "Mancato!",
        "number": "12",
        "suit": "F",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_12_F.png"
    },
    {
        "name": "Mancato!",
        "number": "13",
        "suit": "F",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_13_F.png"
    },
    {
        "name": "Mancato!",
        "number": "14",
        "suit": "F",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_14_F.png"
    },
    {
        "name": "Mancato!",
        "number": "2",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_2_P.png"
    },
    {
        "name": "Mancato!",
        "number": "3",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_3_P.png"
    },
    {
        "name": "Mancato!",
        "number": "4",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_4_P.png"
    },
    {
        "name": "Mancato!",
        "number": "5",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_5_P.png"
    },
    {
        "name": "Mancato!",
        "number": "6",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_6_P.png"
    },
    {
        "name": "Mancato!",
        "number": "7",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_7_P.png"
    },
    {
        "name": "Mancato!",
        "number": "8",
        "suit": "P",
        "color": "marrone",
        "action": "schiva",
        "ability": "Puoi schivare un colpo.",
        "range": "colpo",
        "quantity": "0",
        "img": "Mancato!_8_P.png"
    },
    {
        "name": "Cat Balou",
        "number": "9",
        "suit": "Q",
        "color": "marrone",
        "action": "scarta",
        "ability": "Puoi far scartare una carta dalla mano di un giocatore o una a tua scelta tra quelle da lui giocate.",
        "range": "qualsiasi_altro",
        "quantity": "1",
        "img": "Cat Balou_9_Q.png"
    },
    {
        "name": "Cat Balou",
        "number": "10",
        "suit": "Q",
        "color": "marrone",
        "action": "scarta",
        "ability": "Puoi far scartare una carta dalla mano di un giocatore o una a tua scelta tra quelle da lui giocate.",
        "range": "qualsiasi_altro",
        "quantity": "1",
        "img": "Cat Balou_10_Q.png"
    },
    {
        "name": "Cat Balou",
        "number": "11",
        "suit": "Q",
        "color": "marrone",
        "action": "scarta",
        "ability": "Puoi far scartare una carta dalla mano di un giocatore o una a tua scelta tra quelle da lui giocate.",
        "range": "qualsiasi_altro",
        "quantity": "1",
        "img": "Cat Balou_11_Q.png"
    },
    {
        "name": "Cat Balou",
        "number": "13",
        "suit": "C",
        "color": "marrone",
        "action": "scarta",
        "ability": "Puoi far scartare una carta dalla mano di un giocatore o una a tua scelta tra quelle da lui giocate.",
        "range": "qualsiasi_altro",
        "quantity": "1",
        "img": "Cat Balou_13_C.png"
    },
    {
        "name": "Panico!",
        "number": "11",
        "suit": "C",
        "color": "marrone",
        "action": "ruba",
        "ability": "Puoi rubare una carta dalla mano di un giocatore a te vicino (e visibile) o una a tua scelta tra quelle da lui giocate.",
        "range": "vicino_raggiungibile",
        "quantity": "1",
        "img": "Panico!_11_C.png"
    },
    {
        "name": "Panico!",
        "number": "12",
        "suit": "C",
        "color": "marrone",
        "action": "ruba",
        "ability": "Puoi rubare una carta dalla mano di un giocatore a te vicino (e visibile) o una a tua scelta tra quelle da lui giocate.",
        "range": "vicino_raggiungibile",
        "quantity": "1",
        "img": "Panico!_12_C.png"
    },
    {
        "name": "Panico!",
        "number": "14",
        "suit": "C",
        "color": "marrone",
        "action": "ruba",
        "ability": "Puoi rubare una carta dalla mano di un giocatore a te vicino (e visibile) o una a tua scelta tra quelle da lui giocate.",
        "range": "vicino_raggiungibile",
        "quantity": "1",
        "img": "Panico!_14_C.png"
    },
    {
        "name": "Panico!",
        "number": "8",
        "suit": "Q",
        "color": "marrone",
        "action": "ruba",
        "ability": "Puoi rubare una carta dalla mano di un giocatore a te vicino (e visibile) o una a tua scelta tra quelle da lui giocate.",
        "range": "vicino_raggiungibile",
        "quantity": "1",
        "img": "Panico!_8_Q.png"
    },
    {
        "name": "Diligenza",
        "number": "9",
        "suit": "P",
        "color": "marrone",
        "action": "pesca",
        "ability": "Pesca 2 carte.",
        "range": "mazzo",
        "quantity": "2",
        "img": "Diligenza_9_Pa.png"
    },
    {
        "name": "Diligenza",
        "number": "9",
        "suit": "P",
        "color": "marrone",
        "action": "pesca",
        "ability": "Pesca 2 carte.",
        "range": "mazzo",
        "quantity": "2",
        "img": "Diligenza_9_Pb.png"
    },
    {
        "name": "Birra",
        "number": "6",
        "suit": "C",
        "color": "marrone",
        "action": "recupera",
        "ability": "Recuperi 1 punto vita.",
        "range": "me",
        "quantity": "1",
        "img": "Birra_6_C.png"
    },
    {
        "name": "Birra",
        "number": "7",
        "suit": "C",
        "color": "marrone",
        "action": "recupera",
        "ability": "Recuperi 1 punto vita.",
        "range": "me",
        "quantity": "1",
        "img": "Birra_7_C.png"
    },
    {
        "name": "Birra",
        "number": "8",
        "suit": "C",
        "color": "marrone",
        "action": "recupera",
        "ability": "Recuperi 1 punto vita.",
        "range": "me",
        "quantity": "1",
        "img": "Birra_8_C.png"
    },
    {
        "name": "Birra",
        "number": "9",
        "suit": "C",
        "color": "marrone",
        "action": "recupera",
        "ability": "Recuperi 1 punto vita.",
        "range": "me",
        "quantity": "1",
        "img": "Birra_9_C.png"
    },
    {
        "name": "Birra",
        "number": "10",
        "suit": "C",
        "color": "marrone",
        "action": "recupera",
        "ability": "Recuperi 1 punto vita.",
        "range": "me",
        "quantity": "1",
        "img": "Birra_10_C.png"
    },
    {
        "name": "Birra",
        "number": "11",
        "suit": "C",
        "color": "marrone",
        "action": "recupera",
        "ability": "Recuperi 1 punto vita.",
        "range": "me",
        "quantity": "1",
        "img": "Birra_11_C.png"
    },
    {
        "name": "Wells Fargo",
        "number": "3",
        "suit": "C",
        "color": "marrone",
        "action": "pesca",
        "ability": "Pesca 3 carte.",
        "range": "mazzo",
        "quantity": "3",
        "img": "Wells Fargo_3_C.png"
    },
    {
        "name": "Gatling",
        "number": "10",
        "suit": "C",
        "color": "marrone",
        "action": "gatling",
        "ability": "Spara un colpo ad ogni altro giocatore.",
        "range": "tutti",
        "quantity": "0",
        "img": "Gatling_10_C.png"
    },
    {
        "name": "Indiani!",
        "number": "13",
        "suit": "Q",
        "color": "marrone",
        "action": "indiani",
        "ability": "Tutti gli altri scartano un BANG! o perdono 1 punto vita.",
        "range": "tutti",
        "quantity": "0",
        "img": "Indiani!_13_Q.png"
    },
    {
        "name": "Indiani!",
        "number": "14",
        "suit": "Q",
        "color": "marrone",
        "action": "indiani",
        "ability": "Tutti gli altri scartano un BANG! o perdono 1 punto vita.",
        "range": "tutti",
        "quantity": "0",
        "img": "Indiani!_14_Q.png"
    },
    {
        "name": "Emporio",
        "number": "9",
        "suit": "F",
        "color": "marrone",
        "action": "emporio",
        "ability": "Rivela carte quanti i giocatori. Ognuno ne pesca una.",
        "range": "mazzo",
        "quantity": "0",
        "img": "Emporio_9_F.png"
    },
    {
        "name": "Emporio",
        "number": "12",
        "suit": "P",
        "color": "marrone",
        "action": "emporio",
        "ability": "Rivela carte quanti i giocatori. Ognuno ne pesca una.",
        "range": "mazzo",
        "quantity": "0",
        "img": "Emporio_12_P.png"
    },
    {
        "name": "Saloon",
        "number": "5",
        "suit": "C",
        "color": "marrone",
        "action": "saloon",
        "ability": "Scegli se recuperare 1 punto vita o far recuperare 1 punto vita a tutti.",
        "range": "tutti",
        "quantity": "1",
        "img": "Saloon_5_C.png"
    },
    {
        "name": "Mirino",
        "number": "14",
        "suit": "P",
        "color": "blu",
        "action": "visione_personaggio",
        "ability": "Tu vedi gli altri a distanza -1.",
        "range": "me",
        "quantity": "0",
        "img": "Mirino_14_P.png"
    },
    {
        "name": "Schofield",
        "number": "11",
        "suit": "F",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Aumenta la visibilità di 2.",
        "range": "me",
        "quantity": "2",
        "img": "Schofield_11_F.png"
    },
    {
        "name": "Schofield",
        "number": "12",
        "suit": "F",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Aumenta la visibilità di 2.",
        "range": "me",
        "quantity": "2",
        "img": "Schofield_12_F.png"
    },
    {
        "name": "Schofield",
        "number": "13",
        "suit": "P",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Aumenta la visibilità di 2.",
        "range": "me",
        "quantity": "2",
        "img": "Schofield_13_P.png"
    },
    {
        "name": "Rev. Carabine",
        "number": "14",
        "suit": "F",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Aumenta la visibilità di 4.",
        "range": "me",
        "quantity": "4",
        "img": "Rev. Carabine_14_F.png"
    },
    {
        "name": "Volcanic",
        "number": "10",
        "suit": "P",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Puoi giocare quanti BANG! vuoi.",
        "range": "me",
        "quantity": "1",
        "img": "Volcanic_10_P.png"
    },
    {
        "name": "Volcanic",
        "number": "10",
        "suit": "F",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Puoi giocare quanti BANG! vuoi.",
        "range": "me",
        "quantity": "1",
        "img": "Volcanic_10_F.png"
    },
    {
        "name": "Winchester",
        "number": "8",
        "suit": "P",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Aumenta la visibilità di 5.",
        "range": "me",
        "quantity": "5",
        "img": "Winchester_8_P.png"
    },
    {
        "name": "Remington",
        "number": "13",
        "suit": "F",
        "color": "blu_arma",
        "action": "visione_colpo",
        "ability": "Aumenta la visibilità di 3.",
        "range": "me",
        "quantity": "3",
        "img": "Remington_13_F.png"
    },
    {
        "name": "Prigione",
        "number": "10",
        "suit": "P",
        "color": "blu",
        "action": "estrai_prigione",
        "ability": "(se estrai una carta di Cuori) Scarta la Prigione e gioca. Altrimenti scarta la Prigione e salta il turno.",
        "range": "qualsiasi_altro_noSceriffo",
        "quantity": "0",
        "img": "Prigione_10_P.png"
    },
    {
        "name": "Prigione",
        "number": "11",
        "suit": "P",
        "color": "blu",
        "action": "estrai_prigione",
        "ability": "(se estrai una carta di Cuori) Scarta la Prigione e gioca. Altrimenti scarta la Prigione e salta il turno.",
        "range": "qualsiasi_altro_noSceriffo",
        "quantity": "0",
        "img": "Prigione_11_P.png"
    },
    {
        "name": "Prigione",
        "number": "4",
        "suit": "C",
        "color": "blu",
        "action": "estrai_prigione",
        "ability": "(se estrai una carta di Cuori) Scarta la Prigione e gioca. Altrimenti scarta la Prigione e salta il turno.",
        "range": "qualsiasi_altro_noSceriffo",
        "quantity": "0",
        "img": "Prigione_4_C.png"
    },
    {
        "name": "Barile",
        "number": "12",
        "suit": "P",
        "color": "blu",
        "action": "estrai_barile",
        "ability": "(se estrai una carta di Cuori) Conta come un Mancato!",
        "range": "me",
        "quantity": "0",
        "img": "Barile_12_P.png"
    },
    {
        "name": "Barile",
        "number": "13",
        "suit": "P",
        "color": "blu",
        "action": "estrai_barile",
        "ability": "(se estrai una carta di Cuori) Conta come un Mancato!",
        "range": "me",
        "quantity": "0",
        "img": "Barile_13_P.png"
    },
    {
        "name": "Dinamite",
        "number": "2",
        "suit": "C",
        "color": "blu",
        "action": "estrai_dinamite",
        "ability": "(se estrai una carta di Picche compresa tra '2' e '9') Perdi 3 punti vita. Se no passa la Dinamite a sinistra.",
        "range": "me",
        "quantity": "0",
        "img": "Dinamite_2_C.png"
    },
    {
        "name": "Mustang",
        "number": "8",
        "suit": "C",
        "color": "blu",
        "action": "visione_personaggio",
        "ability": "Gli altri ti vedono a distanta +1.",
        "range": "me",
        "quantity": "0",
        "img": "Mustang_8_C.png"
    },
    {
        "name": "Mustang",
        "number": "9",
        "suit": "C",
        "color": "blu",
        "action": "visione_personaggio",
        "ability": "Gli altri ti vedono a distanta +1.",
        "range": "me",
        "quantity": "0",
        "img": "Mustang_9_C.png"
    },
    {
        "name": "Bart Cassidy",
        "number": "1",
        "suit": "Base",
        "color": "personaggio",
        "action": "Bart Cassidy",
        "ability": "Ogni volta che viene ferito, pesca una carta.",
        "range": "Bart Cassidy",
        "quantity": "4",
        "img": "Bart Cassidy_1_Base.png"
    },
    {
        "name": "Black Jack",
        "number": "2",
        "suit": "Base",
        "color": "personaggio",
        "action": "Black Jack",
        "ability": "Mostra la seconda carta che pesca. Se è Cuori o Quadri, pesca una carta in più.",
        "range": "Black Jack",
        "quantity": "4",
        "img": "Black Jack_2_Base.png"
    },
    {
        "name": "Calamity Janet",
        "number": "3",
        "suit": "Base",
        "color": "personaggio",
        "action": "Calamity Janet",
        "ability": "Può giocare le carte BANG! come carte Mancato!, e viceversa.",
        "range": "Calamity Janet",
        "quantity": "4",
        "img": "Calamity Janet_3_Base.png"
    },
    {
        "name": "El Gringo",
        "number": "4",
        "suit": "Base",
        "color": "personaggio",
        "action": "El Gringo",
        "ability": "Ogni volta che viene ferito da un giocatore, pesca una carta dalla mano di quel giocatore.",
        "range": "El Gringo",
        "quantity": "3",
        "img": "El Gringo_4_Base.png"
    },
    {
        "name": "Kit Carlson",
        "number": "5",
        "suit": "Base",
        "color": "personaggio",
        "action": "Kit Carlson",
        "ability": "Guarda le prime tre carte del mazzo e sceglie le due da pescare.",
        "range": "Kit Carlson",
        "quantity": "4",
        "img": "Kit Carlson_5_Base.png"
    },
    {
        "name": "Lucky Duke",
        "number": "6",
        "suit": "Base",
        "color": "personaggio",
        "action": "Lucky Duke",
        "ability": "Ogni volta che deve 'estrarre!', scopre 2 carte e sceglie.",
        "range": "Lucky Duke",
        "quantity": "4",
        "img": "Lucky Duke_6_Base.png"
    },
    {
        "name": "Jesse Jones",
        "number": "7",
        "suit": "Base",
        "color": "personaggio",
        "action": "Jesse Jones",
        "ability": "Può pescare la prima carta dalla mano di un giocatore",
        "range": "Jesse Jones",
        "quantity": "4",
        "img": "Jesse Jones_7_Base.png"
    },
    {
        "name": "Jourdonnais",
        "number": "8",
        "suit": "Base",
        "color": "personaggio",
        "action": "Jourdonnais",
        "ability": "Ogni volta che è bersaglio di un BANG!, può 'estrarre!': se esce Cuori, viene mancato.",
        "range": "Jourdonnais",
        "quantity": "4",
        "img": "Jourdonnais_8_Base.png"
    },
    {
        "name": "Paul Regret",
        "number": "9",
        "suit": "Base",
        "color": "personaggio",
        "action": "Paul Regret",
        "ability": "Tutti i giocatori lo vedono a distanza aumentata di 1.",
        "range": "Paul Regret",
        "quantity": "3",
        "img": "Paul Regret_9_Base.png"
    },
    {
        "name": "Pedro Ramirez",
        "number": "10",
        "suit": "Base",
        "color": "personaggio",
        "action": "Pedro Ramirez",
        "ability": "Può pescare la prima carta dalla cima degli scarti.",
        "range": "Pedro Ramirez",
        "quantity": "4",
        "img": "Pedro Ramirez_10_Base.png"
    },
    {
        "name": "Rose Doolan",
        "number": "11",
        "suit": "Base",
        "color": "personaggio",
        "action": "Rose Doolan",
        "ability": "Vede tutti i giocatori a distanza diminuita di 1.",
        "range": "Rose Doolan",
        "quantity": "4",
        "img": "Rose Doolan_11_Base.png"
    },
    {
        "name": "Sid Ketchum",
        "number": "12",
        "suit": "Base",
        "color": "personaggio",
        "action": "Sid Ketchum",
        "ability": "Può scartare 2 carte per recuperare un punto vita.",
        "range": "Sid Ketchum",
        "quantity": "4",
        "img": "Sid Ketchum_12_Base.png"
    },
    {
        "name": "Slab the Killer",
        "number": "13",
        "suit": "Base",
        "color": "personaggio",
        "action": "Slab the Killer",
        "ability": "Per evitare i suoi BANG! occorrono due carte Mancato!",
        "range": "Slab the Killer",
        "quantity": "4",
        "img": "Slab the Killer_13_Base.png"
    },
    {
        "name": "Suzy Lafayette",
        "number": "14",
        "suit": "Base",
        "color": "personaggio",
        "action": "Suzy Lafayette",
        "ability": "Appena rimane senza carte in mano, pesca una carta.",
        "range": "Suzy Lafayette",
        "quantity": "4",
        "img": "Suzy Lafayette_14_Base.png"
    },
    {
        "name": "Vulture Sam",
        "number": "15",
        "suit": "Base",
        "color": "personaggio",
        "action": "Vulture Sam",
        "ability": "Quando un personaggio è eliminato, prende in mano tutte le carte di quel personaggio.",
        "range": "Vulture Sam",
        "quantity": "4",
        "img": "Vulture Sam_15_Base.png"
    },
    {
        "name": "Willy the Kid",
        "number": "16",
        "suit": "Base",
        "color": "personaggio",
        "action": "Willy the Kid",
        "ability": "Può giocare un numero qualsiasi di carte BANG!",
        "range": "Willy the Kid",
        "quantity": "4",
        "img": "Willy the Kid_16_Base.png"
    }
]

module.exports = card_list;